### ISSUE TITLE
Could you share how to handle Variants like Size, Color in Cart?

### ISSUE THREAD

**Issue by ghost** [colbyfayock/space-jelly-store-workshop#1]
Hello. Thank you so much for this great repo. This is the only one PR explain how to create shopping cart without using Typescript and optimize with React. This is really great.

By the way, please could you share how to handle Variants such as Size, Colors in Cart? I think it really need for merch site.

**Comment by colbyfayock** [comment]
hey @huuphongnguyen 

It's hard to say a "right" way to manage variants like that, as it kind of depends on preference, workflow, and even if you're using a CMS

if you're using flat JSON file for instance, maybe you could do:
```
const products = [
  {
    productID: '1234',
    title: 'My cool T-shirt',
    skus: [
      {
        sku: '1234-asdf',
        title: 'Blue - Large',
        price: '12.20'
      }
    ]
  }
]
```

**Comment by ghost** [comment]
> hey @huuphongnguyen
> 
> It's hard to say a "right" way to manage variants like that, as it kind of depends on preference, workflow, and even if you're using a CMS
> 
> if you're using flat JSON file for instance, maybe you could do:
> 
> ```
> const products = [
>   {
>     productID: '1234',
>     title: 'My cool T-shirt',
>     skus: [
>       {
>         sku: '1234-asdf',
>         title: 'Blue - Large',
>         price: '12.20'
>       }
>     ]
>   }
> ]
> ```

Thank you so much. I got it. :D
