### ISSUE TITLE
No capture of address in stripe checkout 

### ISSUE THREAD

**Issue by shanewmurphy** [colbyfayock/space-jelly-store-workshop#2]
Why sell a T-shirt when you've no address to send it to? 

Your not capturing an address at stripe checkout! It's a pretty basic scenario that an e-commerce site would need a shipping address. Stripe provides us with this scenario with "Create a payment link" with such features as Quantity and Shipping Address 

![Screenshot 2022-09-22 at 14 56 42](https://user-images.githubusercontent.com/3694619/191768498-7d3584ea-fca4-47d3-a76c-55a2fa23d82f.png)

When you create this Payment Link the "id="checkout-button-price_1LfiMzKZXFZOoTWJhT2xXmRU"
In our json file for ID we have "id": "price_1LfiMzKZXFZOoTWJhT2xXmRU",

If I change the ID in the json file to   "id="checkout-button-price_1LfiMzKZXFZOoTWJhT2xXmRU" This does not work see the error in dev tools 

![Screenshot 2022-09-22 at 15 01 46](https://user-images.githubusercontent.com/3694619/191768030-0554d0fb-754d-43d7-a883-eb25781bf02d.png)

How do you implement the json id or attach each buy now button with the "id="checkout-button-price_1LfiMzKZXFZOoTWJhT2xXmRU"

**Comment by colbyfayock** [comment]
thanks for the feedback!
